% set default (dark) theme, read when compiled without extra flags
\colorlet{textcolor}{white!80!gray}
\colorlet{backgroundcolor}{black!30!gray}
\colorlet{urlcolor}{blue!25!white}
\AtBeginDocument{\color{textcolor}}
\newcommand{\otherThemeRef}{\href{https://github.com/DiegoRenner/CV/blob/master/light.pdf}{See light theme}}
\newcommand{\latestVersion}{\href{https://github.com/DiegoRenner/CV/blob/master/dark.pdf}{Get latest version}}
\pagecolor{backgroundcolor}
