% set dark theme, read when compiled with -jobname=dark
\colorlet{textcolor}{white!80!gray}
\colorlet{backgroundcolor}{black!30!gray}
\colorlet{urlcolor}{blue!25!white}
\AtBeginDocument{\color{textcolor}}
\newcommand{\otherThemeRef}{\href{https://github.com/DiegoRenner/CV/blob/master/CV_light.pdf}{See light theme}}
\newcommand{\latestVersion}{\href{https://github.com/DiegoRenner/CV/blob/master/CV_dark.pdf}{Get Latest version}}
\pagecolor{backgroundcolor}
